### ISSUE TITLE
Repeated paragraph (on both page 56 & 58)

### ISSUE THREAD

**Issue by jaredly** [almossawi/badchoices#1]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/112170/36819362-773dc15a-1ca6-11e8-9bf2-6594778359ac.png">

It's here https://github.com/almossawi/badchoices/blob/master/pages/page68.html#L3
and here https://github.com/almossawi/badchoices/blob/master/pages/page66.html#L3

**Comment by almossawi** [comment]
Thank you. Fixed and deployed 👍
